test_bootstrap_failure.byte: failure: This error was triggered on purpose.
