test_execution_failure: error: This error was triggered on purpose.
